[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonk_vault = "2YFURUyjJnbxvLrr3btVcqCSwnki4etLj9A9b3GqSf5s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
